language: php
php: 5.5
install: composer install
script:
- phpunit --testdox --bootstrap vendor/autoload.php tests/phpunit/
deploy:
  provider: heroku
  api_key:
    secure: "g/ZH65AGjZSIMF1IuY6ZJcuf++99V5iRtJv5dyYPgOvdl8pHq69Gia+RIRyvHPhODXacB0Yv2yI1pgvhsdx9nhzguDN/UL79vwlG2IWrkBpauM9gzE0mw+Yj2cweGcKTXvudYwCMPER0vCDD2vpcoTuuuMDgGATig7CbfPd3TTc="
  app:
    master: stp-spid-test-stage